# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clients_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_clients(object):
    def setupUi(self, clients):
        clients.setObjectName("clients")
        clients.resize(400, 300)
        self.exit_button = QtWidgets.QPushButton(clients)
        self.exit_button.setGeometry(QtCore.QRect(230, 260, 111, 32))
        self.exit_button.setObjectName("exit_button")
        self.textBrowser = QtWidgets.QTextBrowser(clients)
        self.textBrowser.setGeometry(QtCore.QRect(60, 90, 281, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(clients)
        self.label.setGeometry(QtCore.QRect(60, 70, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(clients)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.username_line = QtWidgets.QLineEdit(clients)
        self.username_line.setGeometry(QtCore.QRect(130, 40, 113, 21))
        self.username_line.setObjectName("username_line")
        self.submit_button = QtWidgets.QPushButton(clients)
        self.submit_button.setGeometry(QtCore.QRect(255, 35, 91, 32))
        self.submit_button.setObjectName("submit_button")
        self.upload_button = QtWidgets.QPushButton(clients)
        self.upload_button.setGeometry(QtCore.QRect(50, 230, 111, 32))
        self.upload_button.setObjectName("upload_button")
        self.port_label = QtWidgets.QLabel(clients)
        self.port_label.setGeometry(QtCore.QRect(60, 10, 60, 16))
        self.port_label.setObjectName("port_label")
        self.port_lineEdit = QtWidgets.QLineEdit(clients)
        self.port_lineEdit.setGeometry(QtCore.QRect(130, 10, 41, 21))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.kill_button = QtWidgets.QPushButton(clients)
        self.kill_button.setGeometry(QtCore.QRect(230, 230, 113, 32))
        self.kill_button.setObjectName("kill_button")

        self.retranslateUi(clients)
        self.exit_button.clicked.connect(clients.close)
        QtCore.QMetaObject.connectSlotsByName(clients)

    def retranslateUi(self, clients):
        _translate = QtCore.QCoreApplication.translate
        clients.setWindowTitle(_translate("clients", "Client"))
        self.exit_button.setText(_translate("clients", "exit"))
        self.label.setText(_translate("clients", "Status:"))
        self.label_2.setText(_translate("clients", "username:"))
        self.submit_button.setText(_translate("clients", "submit"))
        self.upload_button.setText(_translate("clients", "upload"))
        self.port_label.setText(_translate("clients", "port:"))
        self.port_lineEdit.setText(_translate("clients", "12346"))
        self.kill_button.setText(_translate("clients", "kill"))
