# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server(object):
    def setupUi(self, server):
        server.setObjectName("server")
        server.resize(400, 300)
        self.stop_button = QtWidgets.QPushButton(server)
        self.stop_button.setGeometry(QtCore.QRect(40, 250, 121, 32))
        self.stop_button.setObjectName("stop_button")
        self.exit_button = QtWidgets.QPushButton(server)
        self.exit_button.setGeometry(QtCore.QRect(230, 250, 113, 32))
        self.exit_button.setObjectName("exit_button")
        self.textBrowser = QtWidgets.QTextBrowser(server)
        self.textBrowser.setGeometry(QtCore.QRect(50, 150, 291, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(server)
        self.label.setGeometry(QtCore.QRect(50, 120, 60, 16))
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(server)
        self.start_button.setGeometry(QtCore.QRect(230, 15, 121, 32))
        self.start_button.setObjectName("start_button")
        self.port_label = QtWidgets.QLabel(server)
        self.port_label.setGeometry(QtCore.QRect(50, 20, 60, 16))
        self.port_label.setObjectName("port_label")
        self.port_lineEdit = QtWidgets.QLineEdit(server)
        self.port_lineEdit.setGeometry(QtCore.QRect(90, 20, 51, 21))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.label_2 = QtWidgets.QLabel(server)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.activeUsers_browser = QtWidgets.QTextBrowser(server)
        self.activeUsers_browser.setGeometry(QtCore.QRect(140, 60, 201, 61))
        self.activeUsers_browser.setObjectName("activeUsers_browser")

        self.retranslateUi(server)
        self.exit_button.clicked.connect(server.close)
        QtCore.QMetaObject.connectSlotsByName(server)

    def retranslateUi(self, server):
        _translate = QtCore.QCoreApplication.translate
        server.setWindowTitle(_translate("server", "Server"))
        self.stop_button.setText(_translate("server", "stop (kill)"))
        self.exit_button.setText(_translate("server", "exit"))
        self.label.setText(_translate("server", "Status:"))
        self.start_button.setText(_translate("server", "start listening"))
        self.port_label.setText(_translate("server", "Port:"))
        self.port_lineEdit.setText(_translate("server", "12346"))
        self.label_2.setText(_translate("server", "active users:"))
